FROM node:lts-alpine
RUN npm install -g @angular/cli
WORKDIR /app

# docker build -t angular ./createProject/.
# docker run -itd -v ${PWD}:/app --name angularWeb angular
# docker exec -it angularWeb ng new projectName --directory=.
# sudo chown -R $USER:$(id -gn $USER) ./*
# docker-compose up
# docker-compose exec web commandToRun
# Example: -
# docker-compose exec web ng generate component xyz # to create a component in the project